name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: docker pull nensiravaliya028/node.js-app-cicd:latest
    - name: Delete Old docker container
      run: |
        docker rm -f "node.js-app-cicd-container" || true
    - name: Run Docker Container
      run: |
        docker run -d -p 8080:8080 --name "node.js-app-cicd-container" nensiravaliya028/node.js-app-cicd:latest
