name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub and Build/Push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker build -t nensiravaliya28/node.js-app-cicd:latest .
          docker tag nensiravaliya28/node.js-app-cicd:latest "${DOCKER_USERNAME}/nensiravaliya28/node.js-app-cicd:latest"
          docker push "${DOCKER_USERNAME}/nensiravaliya28/node.js-app-cicd:latest"
