name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub and Build/Push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker build -t "${DOCKER_USERNAME}/node.js-app-cicd:latest" .
          docker tag "${DOCKER_USERNAME}/node.js-app-cicd:latest" "${DOCKER_USERNAME}/node.js-app-cicd:latest"
          docker push "${DOCKER_USERNAME}/node.js-app-cicd:latest"
